version: "2"

services:
  web:
    build: .
    volumes:
    - .:/code
    ports:
    - "8000:8000"
    command: >
      bash -c "./manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
