# Generated by Django 2.1.7 on 2019-03-21 17:50

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now)),
                ('card_url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('qr_code_url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_user', to=settings.AUTH_USER_MODEL)),
                ('original_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='original_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lastcard.Card')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
