# Generated by Django 2.1.7 on 2019-03-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastcard', '0002_auto_20190322_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
